const projects = [
  {
    id: 1,
    title: "Future Talks",
    description: "A freelance website for a career consultancy firm",
    image: "/images/projects/futuretalks.png",
    gitUrl: "https://github.com/johan-naizu/future-talks-backend",
    previewUrl: "https://myfuturetalks.com",
    tag: ["All", "Web"],
  },
  {
    id: 2,
    title: "Tathva'23",
    description: "The official website of Tathva'23",
    image: "/images/projects/t23.png",
    gitUrl: "https://github.com/Tathva-23/tathva-backend",
    previewUrl: "https://23.tathva.org",
    tag: ["All", "Web"],
  },
  {
    id: 3,
    title: "Tathva'22",
    description: "The official website of Tathva'22",
    image: "/images/projects/t22.png",
    gitUrl: "https://github.com/Tathva-22/tathva-22-backend",
    previewUrl: "https://22.tathva.org",
    tag: ["All", "Web"],
  },
  {
    id: 4,
    title: "Ragam'23",
    description: "The official website of Ragam'23",
    image: "/images/projects/r23.png",
    gitUrl: "https://github.com/Ragam23/ragam-23-backend",
    previewUrl: "https://ragam.co.in",
    tag: ["All", "Web"],
  },
  {
    id: 5,
    title: "Sypher",
    description: "A multipurpose discord bot",
    image: "/images/projects/sypher.png",
    gitUrl: "https://github.com/johan-naizu/Sypher",
    previewUrl: "https://sypher.jonaz.tech",
    tag: ["All", "API"],
  },
  {
    id: 6,
    title: "Chatbot",
    description: "A CLI chatbot made with Node.js and ChatGPT API",
    image: "/images/projects/chatbot.webp",
    gitUrl: "https://github.com/johan-naizu/chat-bot",
    tag: ["All", "API"],
  },
];

export default projects;
